# Generated by Django 5.1.1 on 2024-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('Asset_1', 'Asset_1'), ('Asset_2', 'Asset_2'), ('Asset_3', 'Asset_3'), ('Asset_4', 'Asset_4'), ('Asset_5', 'Asset_5'), ('Asset_6', 'Asset_6'), ('Asset_7', 'Asset_7'), ('Asset_8', 'Asset_8'), ('Asset_9', 'Asset_9'), ('Asset_10', 'Asset_10'), ('Asset_11', 'Asset_11'), ('Asset_12', 'Asset_12')], max_length=50)),
                ('seat_number', models.CharField(max_length=10)),
                ('seating_type', models.CharField(choices=[('2TIER', '2TIER'), ('3TIER', '3TIER'), ('HAT', 'HAT')], default='2TIER', max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], default='Available', max_length=10)),
            ],
        ),
    ]
