print("jai shri ram")
x = {"virat":18,"rohit":45,"dhoni":7,"surya":63,"sachine":10}
y = x.copy()
#x.clear()
x.update({"vrushabh":11})
y = x.keys()
print(y)
y = x.items()
print(y)
y = x.values()
y = print(y)
y = x.pop("virat")
print(x)
y = x.popitem()
print(y)
y = x.get("dhoni")
print(y)
