# Generated by Django 5.1.1 on 2024-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('seat_name', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=50)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('2TIER', '2TIER'), ('3TIER', '3TIER'), ('HAT', 'HAT')], default='3TIER', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
